# Close a singular issue without a reproduction
# Triggered by adding the `no-reproduction` label to an issue

name: 🚪 Close issue without a reproduction

on:
  issue:
    types: [labeled]

jobs:
  close-no-repro-issue:
    name: 🚪 Close issue
    if: github.repository == 'remix-run/react-router' && github.event.label.name == 'no-reproduction'
    runs-on: ubuntu-latest
    steps:
      - name: 🚪 Close issue
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh issue comment ${{ github.event.issue.number }} -F ./scripts/close-no-repro-issue.md
          gh issue edit ${{ github.event.issue.number }} --remove-label ${{ github.event.label.name }}
