name: 🧪 Test Workflow for PR Label

on:
  pull_request:
    types: [labeled]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Log
        run: |
          echo "Label: ${{ github.event.label.name }}"
          echo "Branch: ${{ github.event.pull_request.head.ref }}"
